### ISSUE TITLE
uninitialized constant PagSeguro::Url (NameError)

### ISSUE THREAD

**Issue by matheusml** [heavenstudio/pag_seguro#21]
Segui a documentação do GitHub, ou seja:
1) ```gem 'pag_seguro'

2) Adicionar na pasta ```config/initializares/pagseguro.rb``` a linha: ```PagSeguro::Url.environment = :sandbox```

 e obtive o seguinte erro:
```/config/initializers/pagseguro.rb:1:in `<top (required)>': uninitialized constant PagSeguro::Url (NameError)```

Alguma ideia?

**Comment by edsonlima** [comment]
A versão disponível no RubyGems é diferente dessa, embora o número de versão tenha sido mantido. 
Para corrigir, use a gem direto do github, adicionando ao Gemfile:
```ruby
gem 'pag_seguro', :git => 'git://github.com/heavenstudio/pag_seguro'
```
Ainda estou testando, passei desse primeiro problema, mas não sei dizer se a versão do repositório pode ser usada em produção...

**Comment by teonimesic** [comment]
Sincronizei a versão da gem com a do repo e vou dar o issue como encerrado já que não há comentários de que o problema persiste depois do que foi escrito pelo @edsonlima
