### ISSUE TITLE
Número de parcelas sem juros diferentes para cada pagamento

### ISSUE THREAD

**Issue by leosmeira** [heavenstudio/pag_seguro#22]
Realizar a integração com o checkout transparente e informar no parâmetro “maxInstallmentNoInterest” o número de parcelas que você não cobrará juros.

Ver detalhes aqui:
http://forum.pagseguro.uol.com.br/t/11051150/colocar-parcelas-diferentes-sem-juros-no-site

**Comment by teonimesic** [comment]
O escopo dessa gem é oferecer acesso em Ruby à API V2 REST do PagSeguro. Integrar o checkout transparente além de ser muito trabalho não tem muito a ver com o objetivo original projeto.

Existem outros projetos fazendo integração com checkout transparente onde acredito que sua necessidade faça mais sentido: https://github.com/eventick/pagseguro-transparente
